org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

mod.group=at.minecraftschurli.arsmagicalegacy
mod.id=arsmagicalegacy
mod.version=1.5.0
mod.name=Ars Magica: Legacy
mod.vendor=MinecraftschurliMods
mod.authors=Minecraftschurli, IchHabeHunger54
mod.description=Continuation of Ars Magica 2 by Mithion
mod.credits=Mithion for the original mod
mod.logo=logo.png
mod.url=https://www.curseforge.com/minecraft/mc-mods/ars-magica-legacy

java_version=25

github.owner=MinecraftschurliMods
github.repo=Ars-Magica-Legacy

license.name=MIT
license.url=https://opensource.org/licenses/MIT

neogradle.subsystems.conventions.runs.create-default-run-per-type=false

mc_version=26.1-pre-1
mc_version_range=[26.1,25.2)

neo_version=26.1.0.0-alpha.0+pre-1.20260310.230015
neo_version_range=[26.1,26.2)

loader.version=[1,)
junit_version=5.7.1

dependency.geckolib.version=4.7.7
dependency.geckolib.version.range=[4.7.7,4.8)

dependency.curios.version=9.5.1+1.21.1
dependency.curios.version.range=[9.5.1,10)

dependency.jade.version=15.10.3+neoforge
dependency.jade.version.range=[15.10.3,16)

dependency.jei.version=19.22.1.316
dependency.jei.version.range=[19.22,20)

dependency.patchouli.version=1.21.1-93-NEOFORGE
dependency.patchouli.version.range=[1.21.1-93,1.21.2)

dependency.easydatagenlib.version=1.21-1.1.2-SNAPSHOT

mc-publish.curseforge=350734
mc-publish.modrinth=hm4S7JIe
