org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_id=arsmagicalegacy
mod_name=Ars Magica: Legacy
mod_license=MIT
mod_version=1.5.0
mod_group_id=at.minecraftschurli.arsmagicalegacy
mod_authors=Minecraftschurli, IchHabeHunger54
mod_description=Continuation of Ars Magica 2 by Mithion

neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17
mc_version=1.21.1
neo_version=21.1.197
junit_version=5.7.1
loader_version=[1,)

geckolib_version=4.7.7
curios_version=9.5.1+1.21.1
jade_version=15.10.3+neoforge
jei_version=19.22.1.316
patchouli_version=1.21.1-93-NEOFORGE-SNAPSHOT
