modLoader = "javafml"
loaderVersion = "${loader_version}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
enumExtensions = "META-INF/enumextensions.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "[${mc_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "geckolib"
type = "required"
versionRange = "[${geckolib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "patchouli"
type = "required"
versionRange = "[${patchouli_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "curios"
type = "optional"
versionRange = "[${curios_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "jade"
type = "optional"
versionRange = "[${jade_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "jei"
type = "optional"
versionRange = "[${jei_version},)"
ordering = "NONE"
side = "BOTH"
