package at.minecraftschurli.arsmagicalegacy.init;

import at.minecraftschurli.arsmagicalegacy.api.spell.SpellPart;
import at.minecraftschurli.arsmagicalegacy.spell.component.Attract;
import at.minecraftschurli.arsmagicalegacy.spell.component.BanishRain;
import at.minecraftschurli.arsmagicalegacy.spell.component.Blink;
import at.minecraftschurli.arsmagicalegacy.spell.component.Blizzard;
import at.minecraftschurli.arsmagicalegacy.spell.component.Charm;
import at.minecraftschurli.arsmagicalegacy.spell.component.CreateWater;
import at.minecraftschurli.arsmagicalegacy.spell.component.Damage;
import at.minecraftschurli.arsmagicalegacy.spell.component.Daylight;
import at.minecraftschurli.arsmagicalegacy.spell.component.Dig;
import at.minecraftschurli.arsmagicalegacy.spell.component.Disarm;
import at.minecraftschurli.arsmagicalegacy.spell.component.Dispel;
import at.minecraftschurli.arsmagicalegacy.spell.component.DivineIntervention;
import at.minecraftschurli.arsmagicalegacy.spell.component.Drought;
import at.minecraftschurli.arsmagicalegacy.spell.component.Effect;
import at.minecraftschurli.arsmagicalegacy.spell.component.EnderIntervention;
import at.minecraftschurli.arsmagicalegacy.spell.component.Explosion;
import at.minecraftschurli.arsmagicalegacy.spell.component.FallingStar;
import at.minecraftschurli.arsmagicalegacy.spell.component.FireRain;
import at.minecraftschurli.arsmagicalegacy.spell.component.Fling;
import at.minecraftschurli.arsmagicalegacy.spell.component.Forge;
import at.minecraftschurli.arsmagicalegacy.spell.component.Grow;
import at.minecraftschurli.arsmagicalegacy.spell.component.Harvest;
import at.minecraftschurli.arsmagicalegacy.spell.component.Heal;
import at.minecraftschurli.arsmagicalegacy.spell.component.Ignition;
import at.minecraftschurli.arsmagicalegacy.spell.component.Knockback;
import at.minecraftschurli.arsmagicalegacy.spell.component.LifeDrain;
import at.minecraftschurli.arsmagicalegacy.spell.component.LifeTap;
import at.minecraftschurli.arsmagicalegacy.spell.component.Light;
import at.minecraftschurli.arsmagicalegacy.spell.component.ManaBlast;
import at.minecraftschurli.arsmagicalegacy.spell.component.ManaDrain;
import at.minecraftschurli.arsmagicalegacy.spell.component.MeltArmor;
import at.minecraftschurli.arsmagicalegacy.spell.component.Moonrise;
import at.minecraftschurli.arsmagicalegacy.spell.component.PlaceBlock;
import at.minecraftschurli.arsmagicalegacy.spell.component.Plant;
import at.minecraftschurli.arsmagicalegacy.spell.component.Plow;
import at.minecraftschurli.arsmagicalegacy.spell.component.RandomTeleport;
import at.minecraftschurli.arsmagicalegacy.spell.component.Recall;
import at.minecraftschurli.arsmagicalegacy.spell.component.Repel;
import at.minecraftschurli.arsmagicalegacy.spell.component.Rift;
import at.minecraftschurli.arsmagicalegacy.spell.component.Storm;
import at.minecraftschurli.arsmagicalegacy.spell.component.Summon;
import at.minecraftschurli.arsmagicalegacy.spell.component.Telekinesis;
import at.minecraftschurli.arsmagicalegacy.spell.component.Transplace;
import at.minecraftschurli.arsmagicalegacy.spell.component.WizardsAutumn;
import at.minecraftschurli.arsmagicalegacy.spell.modifier.Modifier;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Beam;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Chain;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Channel;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Projectile;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Self;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Touch;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Wave;
import at.minecraftschurli.arsmagicalegacy.spell.shape.AreaOfEffect;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Contingency;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Rune;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Wall;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Zone;
import net.neoforged.neoforge.registries.DeferredHolder;

import java.util.function.Supplier;

public interface AMSpells {
    // @formatter:off
    DeferredHolder<SpellPart, AreaOfEffect>       AREA_OF_EFFECT      = register("area_of_effect",      AreaOfEffect::new);
    DeferredHolder<SpellPart, Beam>               BEAM                = register("beam",                Beam::new);
    DeferredHolder<SpellPart, Chain>              CHAIN               = register("chain",               Chain::new);
    DeferredHolder<SpellPart, Channel>            CHANNEL             = register("channel",             Channel::new);
    DeferredHolder<SpellPart, Projectile>         PROJECTILE          = register("projectile",          Projectile::new);
    DeferredHolder<SpellPart, Rune>               RUNE                = register("rune",                Rune::new);
    DeferredHolder<SpellPart, Self>               SELF                = register("self",                Self::new);
    DeferredHolder<SpellPart, Touch>              TOUCH               = register("touch",               Touch::new);
    DeferredHolder<SpellPart, Wall>               WALL                = register("wall",                Wall::new);
    DeferredHolder<SpellPart, Wave>               WAVE                = register("wave",                Wave::new);
    DeferredHolder<SpellPart, Zone>               ZONE                = register("zone",                Zone::new);
    DeferredHolder<SpellPart, Contingency>        CONTINGENCY_DAMAGE  = register("contingency_damage",  Contingency::new);
    DeferredHolder<SpellPart, Contingency>        CONTINGENCY_DEATH   = register("contingency_death",   Contingency::new);
    DeferredHolder<SpellPart, Contingency>        CONTINGENCY_FALL    = register("contingency_fall",    Contingency::new);
    DeferredHolder<SpellPart, Contingency>        CONTINGENCY_FIRE    = register("contingency_fire",    Contingency::new);
    DeferredHolder<SpellPart, Contingency>        CONTINGENCY_HEALTH  = register("contingency_health",  Contingency::new);

    DeferredHolder<SpellPart, Damage>             DROWNING_DAMAGE     = register("drowning_damage",     Damage::new);
    DeferredHolder<SpellPart, Damage>             FIRE_DAMAGE         = register("fire_damage",         Damage::new);
    DeferredHolder<SpellPart, Damage>             FROST_DAMAGE        = register("frost_damage",        Damage::new);
    DeferredHolder<SpellPart, Damage>             LIGHTNING_DAMAGE    = register("lightning_damage",    Damage::new);
    DeferredHolder<SpellPart, Damage>             MAGIC_DAMAGE        = register("magic_damage",        Damage::new);
    DeferredHolder<SpellPart, Damage>             PHYSICAL_DAMAGE     = register("physical_damage",     Damage::new);
    DeferredHolder<SpellPart, Effect>             ABSORPTION          = register("absorption",          Effect::new);
    DeferredHolder<SpellPart, Effect>             BLINDNESS           = register("blindness",           Effect::new);
    DeferredHolder<SpellPart, Effect>             HASTE               = register("haste",               Effect::new);
    DeferredHolder<SpellPart, Effect>             HEALTH_BOOST        = register("health_boost",        Effect::new);
    DeferredHolder<SpellPart, Effect>             INVISIBILITY        = register("invisibility",        Effect::new);
    DeferredHolder<SpellPart, Effect>             JUMP_BOOST          = register("jump_boost",          Effect::new);
    DeferredHolder<SpellPart, Effect>             LEVITATION          = register("levitation",          Effect::new);
    DeferredHolder<SpellPart, Effect>             NAUSEA              = register("nausea",              Effect::new);
    DeferredHolder<SpellPart, Effect>             NIGHT_VISION        = register("night_vision",        Effect::new);
    DeferredHolder<SpellPart, Effect>             REGENERATION        = register("regeneration",        Effect::new);
    DeferredHolder<SpellPart, Effect>             SLOWNESS            = register("slowness",            Effect::new);
    DeferredHolder<SpellPart, Effect>             SLOW_FALLING        = register("slow_falling",        Effect::new);
    DeferredHolder<SpellPart, Effect>             SWIFTNESS           = register("swiftness",           Effect::new);
    DeferredHolder<SpellPart, Effect>             WATER_BREATHING     = register("water_breathing",     Effect::new);
    DeferredHolder<SpellPart, Effect>             ASTRAL_DISTORTION   = register("astral_distortion",   Effect::new);
    DeferredHolder<SpellPart, Effect>             ENTANGLE            = register("entangle",            Effect::new);
    DeferredHolder<SpellPart, Effect>             FLIGHT              = register("flight",              Effect::new);
    DeferredHolder<SpellPart, Effect>             FROST               = register("frost",               Effect::new);
    DeferredHolder<SpellPart, Effect>             FURY                = register("fury",                Effect::new);
    DeferredHolder<SpellPart, Effect>             GRAVITY_WELL        = register("gravity_well",        Effect::new);
    DeferredHolder<SpellPart, Effect>             REFLECT             = register("reflect",             Effect::new);
    DeferredHolder<SpellPart, Effect>             SCRAMBLE_SYNAPSES   = register("scramble_synapses",   Effect::new);
    DeferredHolder<SpellPart, Effect>             SHIELD              = register("shield",              Effect::new);
    DeferredHolder<SpellPart, Effect>             SHRINK              = register("shrink",              Effect::new);
    DeferredHolder<SpellPart, Effect>             SILENCE             = register("silence",             Effect::new);
    DeferredHolder<SpellPart, Effect>             SWIFT_SWIM          = register("swift_swim",          Effect::new);
    DeferredHolder<SpellPart, Effect>             TEMPORAL_ANCHOR     = register("temporal_anchor",     Effect::new);
    DeferredHolder<SpellPart, Effect>             TRUE_SIGHT          = register("true_sight",          Effect::new);
    DeferredHolder<SpellPart, Effect>             WATERY_GRAVE        = register("watery_grave",        Effect::new);
    DeferredHolder<SpellPart, Attract>            ATTRACT             = register("attract",             Attract::new);
    DeferredHolder<SpellPart, BanishRain>         BANISH_RAIN         = register("banish_rain",         BanishRain::new);
    DeferredHolder<SpellPart, Blink>              BLINK               = register("blink",               Blink::new);
    DeferredHolder<SpellPart, Blizzard>           BLIZZARD            = register("blizzard",            Blizzard::new);
    DeferredHolder<SpellPart, Charm>              CHARM               = register("charm",               Charm::new);
    DeferredHolder<SpellPart, CreateWater>        CREATE_WATER        = register("create_water",        CreateWater::new);
    DeferredHolder<SpellPart, Daylight>           DAYLIGHT            = register("daylight",            Daylight::new);
    DeferredHolder<SpellPart, Dig>                DIG                 = register("dig",                 Dig::new);
    DeferredHolder<SpellPart, Disarm>             DISARM              = register("disarm",              Disarm::new);
    DeferredHolder<SpellPart, Dispel>             DISPEL              = register("dispel",              Dispel::new);
    DeferredHolder<SpellPart, DivineIntervention> DIVINE_INTERVENTION = register("divine_intervention", DivineIntervention::new);
    DeferredHolder<SpellPart, Drought>            DROUGHT             = register("drought",             Drought::new);
    DeferredHolder<SpellPart, EnderIntervention>  ENDER_INTERVENTION  = register("ender_intervention",  EnderIntervention::new);
    DeferredHolder<SpellPart, Explosion>          EXPLOSION           = register("explosion",           Explosion::new);
    DeferredHolder<SpellPart, FallingStar>        FALLING_STAR        = register("falling_star",        FallingStar::new);
    DeferredHolder<SpellPart, FireRain>           FIRE_RAIN           = register("fire_rain",           FireRain::new);
    DeferredHolder<SpellPart, Fling>              FLING               = register("fling",               Fling::new);
    DeferredHolder<SpellPart, Forge>              FORGE               = register("forge",               Forge::new);
    DeferredHolder<SpellPart, Grow>               GROW                = register("grow",                Grow::new);
    DeferredHolder<SpellPart, Harvest>            HARVEST             = register("harvest",             Harvest::new);
    DeferredHolder<SpellPart, Heal>               HEAL                = register("heal",                Heal::new);
    DeferredHolder<SpellPart, Ignition>           IGNITION            = register("ignition",            Ignition::new);
    DeferredHolder<SpellPart, Knockback>          KNOCKBACK           = register("knockback",           Knockback::new);
    DeferredHolder<SpellPart, LifeDrain>          LIFE_DRAIN          = register("life_drain",          LifeDrain::new);
    DeferredHolder<SpellPart, LifeTap>            LIFE_TAP            = register("life_tap",            LifeTap::new);
    DeferredHolder<SpellPart, Light>              LIGHT               = register("light",               Light::new);
    DeferredHolder<SpellPart, ManaBlast>          MANA_BLAST          = register("mana_blast",          ManaBlast::new);
    DeferredHolder<SpellPart, ManaDrain>          MANA_DRAIN          = register("mana_drain",          ManaDrain::new);
    DeferredHolder<SpellPart, MeltArmor>          MELT_ARMOR          = register("melt_armor",          MeltArmor::new);
    DeferredHolder<SpellPart, Moonrise>           MOONRISE            = register("moonrise",            Moonrise::new);
    DeferredHolder<SpellPart, PlaceBlock>         PLACE_BLOCK         = register("place_block",         PlaceBlock::new);
    DeferredHolder<SpellPart, Plant>              PLANT               = register("plant",               Plant::new);
    DeferredHolder<SpellPart, Plow>               PLOW                = register("plow",                Plow::new);
    DeferredHolder<SpellPart, RandomTeleport>     RANDOM_TELEPORT     = register("random_teleport",     RandomTeleport::new);
    DeferredHolder<SpellPart, Recall>             RECALL              = register("recall",              Recall::new);
    DeferredHolder<SpellPart, Repel>              REPEL               = register("repel",               Repel::new);
    DeferredHolder<SpellPart, Rift>               RIFT                = register("rift",                Rift::new);
    DeferredHolder<SpellPart, Storm>              STORM               = register("storm",               Storm::new);
    DeferredHolder<SpellPart, Summon>             SUMMON              = register("summon",              Summon::new);
    //DeferredHolder<SpellPart, Telekinesis>        TELEKINESIS         = register("telekinesis",         Telekinesis::new);
    DeferredHolder<SpellPart, Transplace>         TRANSPLACE          = register("transplace",          Transplace::new);
    DeferredHolder<SpellPart, WizardsAutumn>      WIZARDS_AUTUMN      = register("wizards_autumn",      WizardsAutumn::new);

    DeferredHolder<SpellPart, Modifier>           BOUNCE              = register("bounce",              Modifier::new);
    DeferredHolder<SpellPart, Modifier>           COLOR               = register("color",               Modifier::new);
    DeferredHolder<SpellPart, Modifier>           DAMAGE              = register("damage",              Modifier::new);
    DeferredHolder<SpellPart, Modifier>           DISMEMBERING        = register("dismembering",        Modifier::new);
    DeferredHolder<SpellPart, Modifier>           DURATION            = register("duration",            Modifier::new);
    DeferredHolder<SpellPart, Modifier>           EFFECT_POWER        = register("effect_power",        Modifier::new);
    DeferredHolder<SpellPart, Modifier>           GRAVITY             = register("gravity",             Modifier::new);
    DeferredHolder<SpellPart, Modifier>           HEALING             = register("healing",             Modifier::new);
    DeferredHolder<SpellPart, Modifier>           LUNAR               = register("lunar",               Modifier::new);
    DeferredHolder<SpellPart, Modifier>           MINING_POWER        = register("mining_power",        Modifier::new);
    DeferredHolder<SpellPart, Modifier>           PIERCING            = register("piercing",            Modifier::new);
    DeferredHolder<SpellPart, Modifier>           PROSPERITY          = register("prosperity",          Modifier::new);
    DeferredHolder<SpellPart, Modifier>           RANGE               = register("range",               Modifier::new);
    DeferredHolder<SpellPart, Modifier>           RUNE_POWER          = register("rune_power",          Modifier::new);
    DeferredHolder<SpellPart, Modifier>           SILK_TOUCH          = register("silk_touch",          Modifier::new);
    DeferredHolder<SpellPart, Modifier>           SOLAR               = register("solar",               Modifier::new);
    DeferredHolder<SpellPart, Modifier>           TARGET_NON_SOLID    = register("target_non_solid",    Modifier::new);
    DeferredHolder<SpellPart, Modifier>           VELOCITY            = register("velocity",            Modifier::new);
    // @formatter:on

    private static <T extends SpellPart> DeferredHolder<SpellPart, T> register(String name, Supplier<T> supplier) {
        return AMRegistries.SPELL_PARTS.register(name, supplier);
    }

    /**
     * Empty method used for classloading this class.
     */
    static void init() {
    }
}
