package at.minecraftschurli.arsmagicalegacy.init;

import at.minecraftschurli.arsmagicalegacy.api.ArsMagicaApi;
import at.minecraftschurli.arsmagicalegacy.api.spell.SpellIngredient;
import at.minecraftschurli.arsmagicalegacy.api.spell.SpellModifier;
import at.minecraftschurli.arsmagicalegacy.api.spell.SpellPart;
import at.minecraftschurli.arsmagicalegacy.api.spell.SpellStat;
import at.minecraftschurli.arsmagicalegacy.api.spell.SpellStatModifier;
import at.minecraftschurli.arsmagicalegacy.spell.ItemSpellIngredient;
import at.minecraftschurli.arsmagicalegacy.spell.SpellModifiers;
import at.minecraftschurli.arsmagicalegacy.spell.component.Attract;
import at.minecraftschurli.arsmagicalegacy.spell.component.BanishRain;
import at.minecraftschurli.arsmagicalegacy.spell.component.Blink;
import at.minecraftschurli.arsmagicalegacy.spell.component.Blizzard;
import at.minecraftschurli.arsmagicalegacy.spell.component.Charm;
import at.minecraftschurli.arsmagicalegacy.spell.component.CreateWater;
import at.minecraftschurli.arsmagicalegacy.spell.component.Damage;
import at.minecraftschurli.arsmagicalegacy.spell.component.Daylight;
import at.minecraftschurli.arsmagicalegacy.spell.component.Dig;
import at.minecraftschurli.arsmagicalegacy.spell.component.Disarm;
import at.minecraftschurli.arsmagicalegacy.spell.component.Dispel;
import at.minecraftschurli.arsmagicalegacy.spell.component.DivineIntervention;
import at.minecraftschurli.arsmagicalegacy.spell.component.Drought;
import at.minecraftschurli.arsmagicalegacy.spell.component.Effect;
import at.minecraftschurli.arsmagicalegacy.spell.component.EnderIntervention;
import at.minecraftschurli.arsmagicalegacy.spell.component.Explosion;
import at.minecraftschurli.arsmagicalegacy.spell.component.FallingStar;
import at.minecraftschurli.arsmagicalegacy.spell.component.FireRain;
import at.minecraftschurli.arsmagicalegacy.spell.component.Fling;
import at.minecraftschurli.arsmagicalegacy.spell.component.Forge;
import at.minecraftschurli.arsmagicalegacy.spell.component.Frost;
import at.minecraftschurli.arsmagicalegacy.spell.component.Grow;
import at.minecraftschurli.arsmagicalegacy.spell.component.Harvest;
import at.minecraftschurli.arsmagicalegacy.spell.component.Heal;
import at.minecraftschurli.arsmagicalegacy.spell.component.Ignition;
import at.minecraftschurli.arsmagicalegacy.spell.component.Knockback;
import at.minecraftschurli.arsmagicalegacy.spell.component.LifeDrain;
import at.minecraftschurli.arsmagicalegacy.spell.component.LifeTap;
import at.minecraftschurli.arsmagicalegacy.spell.component.Light;
import at.minecraftschurli.arsmagicalegacy.spell.component.ManaBlast;
import at.minecraftschurli.arsmagicalegacy.spell.component.ManaDrain;
import at.minecraftschurli.arsmagicalegacy.spell.component.MeltArmor;
import at.minecraftschurli.arsmagicalegacy.spell.component.Moonrise;
import at.minecraftschurli.arsmagicalegacy.spell.component.PlaceBlock;
import at.minecraftschurli.arsmagicalegacy.spell.component.Plant;
import at.minecraftschurli.arsmagicalegacy.spell.component.Plow;
import at.minecraftschurli.arsmagicalegacy.spell.component.RandomTeleport;
import at.minecraftschurli.arsmagicalegacy.spell.component.Recall;
import at.minecraftschurli.arsmagicalegacy.spell.component.Repel;
import at.minecraftschurli.arsmagicalegacy.spell.component.Rift;
import at.minecraftschurli.arsmagicalegacy.spell.component.Storm;
import at.minecraftschurli.arsmagicalegacy.spell.component.Summon;
import at.minecraftschurli.arsmagicalegacy.spell.component.Transplace;
import at.minecraftschurli.arsmagicalegacy.spell.component.WizardsAutumn;
import at.minecraftschurli.arsmagicalegacy.spell.shape.AreaOfEffect;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Beam;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Chain;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Channel;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Contingency;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Projectile;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Rune;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Self;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Touch;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Wall;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Wave;
import at.minecraftschurli.arsmagicalegacy.spell.shape.Zone;
import com.mojang.serialization.MapCodec;
import net.minecraft.world.effect.MobEffects;
import net.neoforged.neoforge.registries.DeferredHolder;

import java.util.Map;
import java.util.function.Supplier;

public interface AMSpells {
    DeferredHolder<MapCodec<? extends SpellIngredient>, MapCodec<ItemSpellIngredient>> ITEM_SPELL_INGREDIENT = AMRegistries.SPELL_INGREDIENTS.register("item", () -> ItemSpellIngredient.CODEC);

    // @formatter:off
    SpellStat BOUNCE_STAT           = new SpellStat(ArsMagicaApi.modLoc("bounce"));
    SpellStat DAMAGE_STAT           = new SpellStat(ArsMagicaApi.modLoc("damage"));
    SpellStat DISMEMBERING_STAT     = new SpellStat(ArsMagicaApi.modLoc("dismembering"));
    SpellStat DURATION_STAT         = new SpellStat(ArsMagicaApi.modLoc("duration"));
    SpellStat EFFECT_POWER_STAT     = new SpellStat(ArsMagicaApi.modLoc("effect_power"));
    SpellStat FORTUNE_STAT          = new SpellStat(ArsMagicaApi.modLoc("fortune"));
    SpellStat GRAVITY_STAT          = new SpellStat(ArsMagicaApi.modLoc("gravity"));
    SpellStat HEALING_STAT          = new SpellStat(ArsMagicaApi.modLoc("healing"));
    SpellStat MINING_POWER_STAT     = new SpellStat(ArsMagicaApi.modLoc("mining_power"));
    SpellStat PIERCING_STAT         = new SpellStat(ArsMagicaApi.modLoc("piercing"));
    SpellStat RANGE_STAT            = new SpellStat(ArsMagicaApi.modLoc("range"));
    SpellStat RUNE_POWER_STAT       = new SpellStat(ArsMagicaApi.modLoc("rune_power"));
    SpellStat SILK_TOUCH_STAT       = new SpellStat(ArsMagicaApi.modLoc("silk_touch"));
    SpellStat SPEED_STAT            = new SpellStat(ArsMagicaApi.modLoc("speed"));
    SpellStat TARGET_NON_SOLID_STAT = new SpellStat(ArsMagicaApi.modLoc("target_non_solid"));

    DeferredHolder<SpellPart, AreaOfEffect> AREA_OF_EFFECT     = register("area_of_effect",     AreaOfEffect::new);
    DeferredHolder<SpellPart, Beam>         BEAM               = register("beam",               Beam::new);
    DeferredHolder<SpellPart, Chain>        CHAIN              = register("chain",              Chain::new);
    DeferredHolder<SpellPart, Channel>      CHANNEL            = register("channel",            Channel::new);
    DeferredHolder<SpellPart, Projectile>   PROJECTILE         = register("projectile",         Projectile::new);
    DeferredHolder<SpellPart, Rune>         RUNE               = register("rune",               Rune::new);
    DeferredHolder<SpellPart, Self>         SELF               = register("self",               Self::new);
    DeferredHolder<SpellPart, Touch>        TOUCH              = register("touch",              Touch::new);
    DeferredHolder<SpellPart, Wall>         WALL               = register("wall",               Wall::new);
    DeferredHolder<SpellPart, Wave>         WAVE               = register("wave",               Wave::new);
    DeferredHolder<SpellPart, Zone>         ZONE               = register("zone",               Zone::new);
    DeferredHolder<SpellPart, Contingency>  CONTINGENCY_DAMAGE = register("contingency_damage", Contingency::new);
    DeferredHolder<SpellPart, Contingency>  CONTINGENCY_DEATH  = register("contingency_death",  Contingency::new);
    DeferredHolder<SpellPart, Contingency>  CONTINGENCY_FALL   = register("contingency_fall",   Contingency::new);
    DeferredHolder<SpellPart, Contingency>  CONTINGENCY_FIRE   = register("contingency_fire",   Contingency::new);
    DeferredHolder<SpellPart, Contingency>  CONTINGENCY_HEALTH = register("contingency_health", Contingency::new);

    DeferredHolder<SpellPart, Damage>             DROWNING_DAMAGE     = register("drowning_damage",     Damage::new);
    DeferredHolder<SpellPart, Damage>             FIRE_DAMAGE         = register("fire_damage",         Damage::new);
    DeferredHolder<SpellPart, Damage>             FROST_DAMAGE        = register("frost_damage",        Damage::new);
    DeferredHolder<SpellPart, Damage>             LIGHTNING_DAMAGE    = register("lightning_damage",    Damage::new);
    DeferredHolder<SpellPart, Damage>             MAGIC_DAMAGE        = register("magic_damage",        Damage::new);
    DeferredHolder<SpellPart, Damage>             PHYSICAL_DAMAGE     = register("physical_damage",     Damage::new);
    DeferredHolder<SpellPart, Effect>             ABSORPTION          = register("absorption",          () -> new Effect(MobEffects.ABSORPTION));
    DeferredHolder<SpellPart, Effect>             BLINDNESS           = register("blindness",           () -> new Effect(MobEffects.BLINDNESS));
    DeferredHolder<SpellPart, Effect>             HASTE               = register("haste",               () -> new Effect(MobEffects.DIG_SPEED));
    DeferredHolder<SpellPart, Effect>             HEALTH_BOOST        = register("health_boost",        () -> new Effect(MobEffects.HEALTH_BOOST));
    DeferredHolder<SpellPart, Effect>             INVISIBILITY        = register("invisibility",        () -> new Effect(MobEffects.INVISIBILITY));
    DeferredHolder<SpellPart, Effect>             JUMP_BOOST          = register("jump_boost",          () -> new Effect(MobEffects.JUMP));
    DeferredHolder<SpellPart, Effect>             LEVITATION          = register("levitation",          () -> new Effect(MobEffects.LEVITATION));
    DeferredHolder<SpellPart, Effect>             NAUSEA              = register("nausea",              () -> new Effect(MobEffects.CONFUSION));
    DeferredHolder<SpellPart, Effect>             NIGHT_VISION        = register("night_vision",        () -> new Effect(MobEffects.NIGHT_VISION));
    DeferredHolder<SpellPart, Effect>             REGENERATION        = register("regeneration",        () -> new Effect(MobEffects.REGENERATION));
    DeferredHolder<SpellPart, Effect>             RESISTANCE          = register("resistance",          () -> new Effect(MobEffects.DAMAGE_RESISTANCE));
    DeferredHolder<SpellPart, Effect>             SLOWNESS            = register("slowness",            () -> new Effect(MobEffects.MOVEMENT_SLOWDOWN));
    DeferredHolder<SpellPart, Effect>             SLOW_FALLING        = register("slow_falling",        () -> new Effect(MobEffects.SLOW_FALLING));
    DeferredHolder<SpellPart, Effect>             SWIFTNESS           = register("swiftness",           () -> new Effect(MobEffects.MOVEMENT_SPEED));
    DeferredHolder<SpellPart, Effect>             WATER_BREATHING     = register("water_breathing",     () -> new Effect(MobEffects.WATER_BREATHING));
    DeferredHolder<SpellPart, Effect>             ASTRAL_DISTORTION   = register("astral_distortion",   () -> new Effect(AMMobEffects.ASTRAL_DISTORTION));
    DeferredHolder<SpellPart, Effect>             ENTANGLE            = register("entangle",            () -> new Effect(AMMobEffects.ENTANGLE));
    DeferredHolder<SpellPart, Effect>             FLIGHT              = register("flight",              () -> new Effect(AMMobEffects.FLIGHT));
    DeferredHolder<SpellPart, Effect>             FURY                = register("fury",                () -> new Effect(AMMobEffects.FURY));
    DeferredHolder<SpellPart, Effect>             GRAVITY_WELL        = register("gravity_well",        () -> new Effect(AMMobEffects.GRAVITY_WELL));
    DeferredHolder<SpellPart, Effect>             REFLECT             = register("reflect",             () -> new Effect(AMMobEffects.REFLECT));
    DeferredHolder<SpellPart, Effect>             SCRAMBLE_SYNAPSES   = register("scramble_synapses",   () -> new Effect(AMMobEffects.SCRAMBLE_SYNAPSES));
    DeferredHolder<SpellPart, Effect>             SHRINK              = register("shrink",              () -> new Effect(AMMobEffects.SHRINK));
    DeferredHolder<SpellPart, Effect>             SILENCE             = register("silence",             () -> new Effect(AMMobEffects.SILENCE));
    DeferredHolder<SpellPart, Effect>             SWIFT_SWIM          = register("swift_swim",          () -> new Effect(AMMobEffects.SWIFT_SWIM));
    DeferredHolder<SpellPart, Effect>             TEMPORAL_ANCHOR     = register("temporal_anchor",     () -> new Effect(AMMobEffects.TEMPORAL_ANCHOR));
    DeferredHolder<SpellPart, Effect>             TRUE_SIGHT          = register("true_sight",          () -> new Effect(AMMobEffects.TRUE_SIGHT));
    DeferredHolder<SpellPart, Effect>             WATERY_GRAVE        = register("watery_grave",        () -> new Effect(AMMobEffects.WATERY_GRAVE));
    DeferredHolder<SpellPart, Attract>            ATTRACT             = register("attract",             Attract::new);
    DeferredHolder<SpellPart, BanishRain>         BANISH_RAIN         = register("banish_rain",         BanishRain::new);
    DeferredHolder<SpellPart, Blink>              BLINK               = register("blink",               Blink::new);
    DeferredHolder<SpellPart, Blizzard>           BLIZZARD            = register("blizzard",            Blizzard::new);
    DeferredHolder<SpellPart, Charm>              CHARM               = register("charm",               Charm::new);
    DeferredHolder<SpellPart, CreateWater>        CREATE_WATER        = register("create_water",        CreateWater::new);
    DeferredHolder<SpellPart, Daylight>           DAYLIGHT            = register("daylight",            Daylight::new);
    DeferredHolder<SpellPart, Dig>                DIG                 = register("dig",                 Dig::new);
    DeferredHolder<SpellPart, Disarm>             DISARM              = register("disarm",              Disarm::new);
    DeferredHolder<SpellPart, Dispel>             DISPEL              = register("dispel",              Dispel::new);
    DeferredHolder<SpellPart, DivineIntervention> DIVINE_INTERVENTION = register("divine_intervention", DivineIntervention::new);
    DeferredHolder<SpellPart, Drought>            DROUGHT             = register("drought",             Drought::new);
    DeferredHolder<SpellPart, EnderIntervention>  ENDER_INTERVENTION  = register("ender_intervention",  EnderIntervention::new);
    DeferredHolder<SpellPart, Explosion>          EXPLOSION           = register("explosion",           Explosion::new);
    DeferredHolder<SpellPart, FallingStar>        FALLING_STAR        = register("falling_star",        FallingStar::new);
    DeferredHolder<SpellPart, FireRain>           FIRE_RAIN           = register("fire_rain",           FireRain::new);
    DeferredHolder<SpellPart, Fling>              FLING               = register("fling",               Fling::new);
    DeferredHolder<SpellPart, Forge>              FORGE               = register("forge",               Forge::new);
    DeferredHolder<SpellPart, Frost>              FROST               = register("frost",               Frost::new);
    DeferredHolder<SpellPart, Grow>               GROW                = register("grow",                Grow::new);
    DeferredHolder<SpellPart, Harvest>            HARVEST             = register("harvest",             Harvest::new);
    DeferredHolder<SpellPart, Heal>               HEAL                = register("heal",                Heal::new);
    DeferredHolder<SpellPart, Ignition>           IGNITION            = register("ignition",            Ignition::new);
    DeferredHolder<SpellPart, Knockback>          KNOCKBACK           = register("knockback",           Knockback::new);
    DeferredHolder<SpellPart, LifeDrain>          LIFE_DRAIN          = register("life_drain",          LifeDrain::new);
    DeferredHolder<SpellPart, LifeTap>            LIFE_TAP            = register("life_tap",            LifeTap::new);
    DeferredHolder<SpellPart, Light>              LIGHT               = register("light",               Light::new);
    DeferredHolder<SpellPart, ManaBlast>          MANA_BLAST          = register("mana_blast",          ManaBlast::new);
    DeferredHolder<SpellPart, ManaDrain>          MANA_DRAIN          = register("mana_drain",          ManaDrain::new);
    DeferredHolder<SpellPart, MeltArmor>          MELT_ARMOR          = register("melt_armor",          MeltArmor::new);
    DeferredHolder<SpellPart, Moonrise>           MOONRISE            = register("moonrise",            Moonrise::new);
    DeferredHolder<SpellPart, PlaceBlock>         PLACE_BLOCK         = register("place_block",         PlaceBlock::new);
    DeferredHolder<SpellPart, Plant>              PLANT               = register("plant",               Plant::new);
    DeferredHolder<SpellPart, Plow>               PLOW                = register("plow",                Plow::new);
    DeferredHolder<SpellPart, RandomTeleport>     RANDOM_TELEPORT     = register("random_teleport",     RandomTeleport::new);
    DeferredHolder<SpellPart, Recall>             RECALL              = register("recall",              Recall::new);
    DeferredHolder<SpellPart, Repel>              REPEL               = register("repel",               Repel::new);
    DeferredHolder<SpellPart, Rift>               RIFT                = register("rift",                Rift::new);
    DeferredHolder<SpellPart, Storm>              STORM               = register("storm",               Storm::new);
    DeferredHolder<SpellPart, Summon>             SUMMON              = register("summon",              Summon::new);
    //DeferredHolder<SpellPart, Telekinesis>        TELEKINESIS         = register("telekinesis",         Telekinesis::new);
    DeferredHolder<SpellPart, Transplace>         TRANSPLACE          = register("transplace",          Transplace::new);
    DeferredHolder<SpellPart, WizardsAutumn>      WIZARDS_AUTUMN      = register("wizards_autumn",      WizardsAutumn::new);

    DeferredHolder<SpellPart, SpellModifier> BOUNCE           = register("bounce",           () -> new SpellModifier(Map.of(BOUNCE_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> COLOR            = register("color",            () -> new SpellModifier(Map.of()));
    DeferredHolder<SpellPart, SpellModifier> DAMAGE           = register("damage",           () -> new SpellModifier(Map.of(DAMAGE_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> DISMEMBERING     = register("dismembering",     () -> new SpellModifier(Map.of(DISMEMBERING_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> DURATION         = register("duration",         () -> new SpellModifier(Map.of(DURATION_STAT, SpellStatModifier.multiply(2))));
    DeferredHolder<SpellPart, SpellModifier> EFFECT_POWER     = register("effect_power",     () -> new SpellModifier(Map.of(EFFECT_POWER_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> GRAVITY          = register("gravity",          () -> new SpellModifier(Map.of(GRAVITY_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> HEALING          = register("healing",          () -> new SpellModifier(Map.of(HEALING_STAT, SpellStatModifier.multiply(2))));
    DeferredHolder<SpellPart, SpellModifier> LUNAR            = register("lunar",            () -> new SpellModifier(SpellModifiers.lunarStatModifiers()));
    DeferredHolder<SpellPart, SpellModifier> MINING_POWER     = register("mining_power",     () -> new SpellModifier(Map.of(MINING_POWER_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> PIERCING         = register("piercing",         () -> new SpellModifier(Map.of(PIERCING_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> PROSPERITY       = register("prosperity",       () -> new SpellModifier(Map.of(FORTUNE_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> RANGE            = register("range",            () -> new SpellModifier(Map.of(RANGE_STAT, SpellStatModifier.multiply(2))));
    DeferredHolder<SpellPart, SpellModifier> RUNE_POWER       = register("rune_power",       () -> new SpellModifier(Map.of(RUNE_POWER_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> SILK_TOUCH       = register("silk_touch",       () -> new SpellModifier(Map.of(SILK_TOUCH_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> SOLAR            = register("solar",            () -> new SpellModifier(SpellModifiers.solarStatModifiers()));
    DeferredHolder<SpellPart, SpellModifier> TARGET_NON_SOLID = register("target_non_solid", () -> new SpellModifier(Map.of(TARGET_NON_SOLID_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> VELOCITY         = register("velocity",         () -> new SpellModifier(Map.of(SPEED_STAT, SpellStatModifier.addMultipliedBase(0.5))));
    // @formatter:on

    private static <T extends SpellPart> DeferredHolder<SpellPart, T> register(String name, Supplier<T> supplier) {
        return AMRegistries.SPELL_PARTS.register(name, supplier);
    }

    /**
     * Empty method used for classloading this class.
     */
    static void init() {
    }
}
