package at.minecraftschurli.arsmagicalegacy.api.etherium;

import at.minecraftschurli.arsmagicalegacy.api.ArsMagicaApi;
import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.core.registries.Registries;
import net.minecraft.util.ExtraCodecs;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.registries.datamaps.DataMapType;
import org.jetbrains.annotations.Nullable;

/**
 * Represents an obelisk fuel.
 *
 * @param burnTime        The burn time of the obelisk fuel, in ticks.
 * @param etheriumPerTick The etherium generated by the obelisk fuel each tick.
 */
public record ObeliskFuel(int burnTime, int etheriumPerTick) {
    public static final Codec<ObeliskFuel> CODEC = RecordCodecBuilder.create(inst -> inst.group(
        ExtraCodecs.POSITIVE_INT.fieldOf("burn_time").forGetter(ObeliskFuel::burnTime),
        ExtraCodecs.POSITIVE_INT.fieldOf("etherium_per_tick").forGetter(ObeliskFuel::etheriumPerTick)
    ).apply(inst, ObeliskFuel::new));
    public static final DataMapType<Item, ObeliskFuel> DATA_MAP = DataMapType.builder(ArsMagicaApi.id("obelisk_fuel"), Registries.ITEM, CODEC)
        .synced(CODEC, true)
        .build();

    /**
     * @return The total etherium that burning the obelisk fuel will generate.
     */
    public int totalEtherium() {
        return burnTime * etheriumPerTick;
    }

    /**
     * @param stack The {@link ItemStack} to get the {@link ObeliskFuel} for.
     * @return The {@link ObeliskFuel} for the given {@link ItemStack}, or null if no such {@link ObeliskFuel} exists.
     */
    @Nullable
    public static ObeliskFuel getFuel(ItemStack stack) {
        return stack.typeHolder().getData(DATA_MAP);
    }

    /**
     * @param stack The {@link ItemStack} to check.
     * @return Whether the given {@link ItemStack} is an {@link ObeliskFuel} or not.
     */
    public static boolean isFuel(ItemStack stack) {
        return getFuel(stack) != null;
    }
}
